version: '3.8'
services:
  backend:
    build:
      context: .
    command: uvicorn main:app --reload --proxy-headers --host 0.0.0.0 --port 82
    expose:
      - 82
    volumes:
      - ./app:/app_d/
    environment:
      - RUTA_MYSQL=mysql+pymysql://root@${DB}:3306/test_productos


  nginx:
    image: nginx:latest
    # ports:
    #   - "80:80"
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=test-dos.diego-luque.com
      - LETSENCRYPT_HOST=test-dos.diego-luque.com
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  default:
    name: web_private_red_webapps
    #name: database_catalogo-network
    external: true