version: '3.8'

services:
  app:
    build: .
    ports:
      - 8002:8000
    environment:
      - RUTA_MYSQL=mysql+pymysql://root@mariadb:3306/test_productos
      - VIRTUAL_HOST=project1.diego-luque.com, project1.diego-luque.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=project1.diego-luque.com, project1.diego-luque.com
    volumes:
      - ./app:/app_d/
    

networks:
  default:
    name: docker_phpmyadmin_mysql_default
    external: true
