version: '3.8'
services:
  backend:
    build:
      context: .
    command: uvicorn main:app --host 0.0.0.0 --port 80
    # ports:
    #   - 8000:80
    environment:
      - RUTA_MYSQL=mysql+pymysql://root@mariadb:3306/test_productos
      - VIRTUAL_HOST=test-dos.diego-luque.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=test-dos.diego-luque.com


networks:
  default:
     name: web_private_red_webapps
     external: true